[build]
publish = "dist"
functions = "netlify/functions"

[context.prod]
command = "npm run build:prod"

[context.deploy-preview]
command = "npm run build:test"

[context.branch-deploy]
command = "npm run build:test"

[dev]
command = "npm run dev"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-emails"
